image: "ruby:2.2"

before_script:
  - export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  - apt-get update
  - apt-get install -y git-annex
  - gem install --bindir /usr/local/bin bundler
  - cp config.yml.example config.yml
  - bundle install

#ruby 2.2
rspec:
  script:
    - bundle exec rspec spec
  tags:
    - ruby
  except:
    - tags

rubocop:
  script: 
    - bundle exec rubocop
  tags:
    - ruby
  except:
    - tags

#ruby 2.1
rspec:ruby2.1:
  image: ruby:2.1
  script:
    - bundle exec rspec spec
  tags:
    - ruby
  except:
    - tags

rubocop:ruby2.1:
  image: ruby:2.1
  script:
    - bundle exec rubocop
  tags:
    - ruby
  except:
    - tags
